module WorldSurveysHelper
  def spawn_world_surveys
    time = Time.now
    [
      create(:world_survey,
             system: "SHINRARTA DEZHRA",
             commander: "Marlon Blake",
             world: "A 5",
             world_type: "High Metal Content",
             terraformable: false,
             gravity: 0.99,
             terrain_difficulty: 2,
             arsenic: true,
             germanium: true,
             molybdenum: true,
             niobium: true,
             polonium: true,
             updated_at: time - 10.days,
             created_at: time - 10.days),
      create(:world_survey,
             system: "NGANJI",
             commander: "Finwen",
             world: "B 3",
             world_type: "High Metal Content",
             terraformable: false,
             gravity: 1.47,
             terrain_difficulty: 3,
             carbon: true,
             iron: true,
             nickel: true,
             phosphorus: true,
             sulphur: true,
             chromium: true,
             germanium: true,
             manganese: true,
             tin: true,
             antimony: true,
             updated_at: time - 5.days,
             created_at: time - 5.days),
      create(:world_survey,
             system: "SHINRARTA DEZHRA",
             commander: "Dommaarraa", # Thanks for the mats spreadsheet!
             world: "A 5",
             world_type: "High Metal Content",
             terraformable: false,
             gravity: 0.99,
             terrain_difficulty: 2,
             carbon: true,
             iron: true,
             nickel: true,
             phosphorus: true,
             sulphur: true,
             manganese: true,
             selenium: true,
             molybdenum: true,
             niobium: true,
             updated_at: time - 1.days,
             created_at: time - 1.days),
    ]
  end
end
