module V2
  class WorldSurveyV1Serializer < ActiveModel::Serializer
    attributes :id,
               :system,
               :commander,
               :world,
               :notes,
               :carbon,
               :iron,
               :nickel,
               :phosphorus,
               :sulphur,
               :arsenic,
               :chromium,
               :germanium,
               :manganese,
               :selenium,
               :vanadium,
               :zinc,
               :zirconium,
               :cadmium,
               :mercury,
               :molybdenum,
               :niobium,
               :tin,
               :tungsten,
               :antimony,
               :polonium,
               :ruthenium,
               :technetium,
               :tellurium,
               :yttrium,
               :updated_at,
               :created_at
  end
end
