require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WorldSurveysController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WorldSurvey. As you add validations to WorldSurvey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorldSurveysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all world_surveys as @world_surveys" do
      world_survey = WorldSurvey.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:world_surveys)).to eq([world_survey])
    end
  end

  describe "GET #show" do
    it "assigns the requested world_survey as @world_survey" do
      world_survey = WorldSurvey.create! valid_attributes
      get :show, {:id => world_survey.to_param}, valid_session
      expect(assigns(:world_survey)).to eq(world_survey)
    end
  end

  describe "GET #new" do
    it "assigns a new world_survey as @world_survey" do
      get :new, {}, valid_session
      expect(assigns(:world_survey)).to be_a_new(WorldSurvey)
    end
  end

  describe "GET #edit" do
    it "assigns the requested world_survey as @world_survey" do
      world_survey = WorldSurvey.create! valid_attributes
      get :edit, {:id => world_survey.to_param}, valid_session
      expect(assigns(:world_survey)).to eq(world_survey)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WorldSurvey" do
        expect {
          post :create, {:world_survey => valid_attributes}, valid_session
        }.to change(WorldSurvey, :count).by(1)
      end

      it "assigns a newly created world_survey as @world_survey" do
        post :create, {:world_survey => valid_attributes}, valid_session
        expect(assigns(:world_survey)).to be_a(WorldSurvey)
        expect(assigns(:world_survey)).to be_persisted
      end

      it "redirects to the created world_survey" do
        post :create, {:world_survey => valid_attributes}, valid_session
        expect(response).to redirect_to(WorldSurvey.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved world_survey as @world_survey" do
        post :create, {:world_survey => invalid_attributes}, valid_session
        expect(assigns(:world_survey)).to be_a_new(WorldSurvey)
      end

      it "re-renders the 'new' template" do
        post :create, {:world_survey => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested world_survey" do
        world_survey = WorldSurvey.create! valid_attributes
        put :update, {:id => world_survey.to_param, :world_survey => new_attributes}, valid_session
        world_survey.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested world_survey as @world_survey" do
        world_survey = WorldSurvey.create! valid_attributes
        put :update, {:id => world_survey.to_param, :world_survey => valid_attributes}, valid_session
        expect(assigns(:world_survey)).to eq(world_survey)
      end

      it "redirects to the world_survey" do
        world_survey = WorldSurvey.create! valid_attributes
        put :update, {:id => world_survey.to_param, :world_survey => valid_attributes}, valid_session
        expect(response).to redirect_to(world_survey)
      end
    end

    context "with invalid params" do
      it "assigns the world_survey as @world_survey" do
        world_survey = WorldSurvey.create! valid_attributes
        put :update, {:id => world_survey.to_param, :world_survey => invalid_attributes}, valid_session
        expect(assigns(:world_survey)).to eq(world_survey)
      end

      it "re-renders the 'edit' template" do
        world_survey = WorldSurvey.create! valid_attributes
        put :update, {:id => world_survey.to_param, :world_survey => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested world_survey" do
      world_survey = WorldSurvey.create! valid_attributes
      expect {
        delete :destroy, {:id => world_survey.to_param}, valid_session
      }.to change(WorldSurvey, :count).by(-1)
    end

    it "redirects to the world_surveys list" do
      world_survey = WorldSurvey.create! valid_attributes
      delete :destroy, {:id => world_survey.to_param}, valid_session
      expect(response).to redirect_to(world_surveys_url)
    end
  end

end
